-- models/worker_transformations/wt_encounter_detail_06.sql

WITH wt_encounter_detail_05 AS (
    SELECT * FROM {{ ref('wt_encounter_detail_05') }}
),

prev_record AS (
    SELECT 
        *,
        LAG(VST_TYPE_CD_SK) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_VST_TYPE_CD_SK,
        LAG(PT_OF_ORIG_CD_SK) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_PT_OF_ORIG_CD_SK,
        LAG(ENCNT_TS) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ENCNT_TS,
        LAG(ADMT_TS) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ADMT_TS,
        LAG(ADMT_CMPLN_TXT) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ADMT_CMPLN_TXT,
        LAG(RE_ADMT_IND) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_RE_ADMT_IND,
        LAG(HSPTL_SRVC_CD_SK) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_HSPTL_SRVC_CD_SK,
        LAG(EXPCT_NUM_OF_INS_PLAN_CNT) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_EXPCT_NUM_OF_INS_PLAN_CNT,
        LAG(ACTL_LEN_OF_STAY_DYS_CNT) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ACTL_LEN_OF_STAY_DYS_CNT,
        LAG(DSCRG_TS) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_DSCRG_TS,
        LAG(DSCRG_STS_CD_SK) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_DSCRG_STS_CD_SK,
        LAG(PTNT_STS_REF_CD) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_PTNT_STS_REF_CD,
        LAG(ADV_DRTCV_PRSNT_TXT) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ADV_DRTCV_PRSNT_TXT,
        LAG(ACCOM_REF_CD) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ACCOM_REF_CD,
        LAG(ALT_ENCNT_TXT) OVER (PARTITION BY ENCNT_SK ORDER BY REC_RANK) AS PREV_ALT_ENCNT_TXT
    FROM wt_encounter_detail_05
)

SELECT 
    *,
    CASE
        WHEN REC_RANK = 1 THEN 1
        WHEN COALESCE(CAST(VST_TYPE_CD_SK AS STRING), 'NULL') != COALESCE(CAST(PREV_VST_TYPE_CD_SK AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(PT_OF_ORIG_CD_SK AS STRING), 'NULL') != COALESCE(CAST(PREV_PT_OF_ORIG_CD_SK AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(ENCNT_TS AS STRING), '1900-01-01 00:00:00') != COALESCE(CAST(PREV_ENCNT_TS AS STRING), '1900-01-01 00:00:00') THEN 1
        WHEN COALESCE(CAST(ADMT_TS AS STRING), '1900-01-01 00:00:00') != COALESCE(CAST(PREV_ADMT_TS AS STRING), '1900-01-01 00:00:00') THEN 1
        WHEN COALESCE(ADMT_CMPLN_TXT, '') != COALESCE(PREV_ADMT_CMPLN_TXT, '') THEN 1
        WHEN COALESCE(CAST(RE_ADMT_IND AS STRING), 'NULL') != COALESCE(CAST(PREV_RE_ADMT_IND AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(HSPTL_SRVC_CD_SK AS STRING), 'NULL') != COALESCE(CAST(PREV_HSPTL_SRVC_CD_SK AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(EXPCT_NUM_OF_INS_PLAN_CNT AS STRING), 'NULL') != COALESCE(CAST(PREV_EXPCT_NUM_OF_INS_PLAN_CNT AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(ACTL_LEN_OF_STAY_DYS_CNT AS STRING), 'NULL') != COALESCE(CAST(PREV_ACTL_LEN_OF_STAY_DYS_CNT AS STRING), 'NULL') THEN 1
        WHEN COALESCE(CAST(DSCRG_TS AS STRING), '1900-01-01 00:00:00') != COALESCE(CAST(PREV_DSCRG_TS AS STRING), '1900-01-01 00:00:00') THEN 1
        WHEN COALESCE(CAST(DSCRG_STS_CD_SK AS STRING), 'NULL') != COALESCE(CAST(PREV_DSCRG_STS_CD_SK AS STRING), 'NULL') THEN 1
        WHEN COALESCE(PTNT_STS_REF_CD, '') != COALESCE(PREV_PTNT_STS_REF_CD, '') THEN 1
        WHEN COALESCE(CAST(ADV_DRTCV_PRSNT_TXT AS STRING), 'NULL') != COALESCE(CAST(PREV_ADV_DRTCV_PRSNT_TXT AS STRING), 'NULL') THEN 1
        WHEN COALESCE(ACCOM_REF_CD, '') != COALESCE(PREV_ACCOM_REF_CD, '') THEN 1
        WHEN COALESCE(ALT_ENCNT_TXT, '') != COALESCE(PREV_ALT_ENCNT_TXT, '') THEN 1
        ELSE 0
    END AS IS_CHANGED
FROM prev_record